#!/usr/bin/perl
$ave=0;$avesqr=0;
while (<>){
        @foo=split;
        push @val,@foo[0];
        $c++ if @foo[0]>0;
        $ave+=@foo[0];
        $avesqr+=@foo[0]**2;
};
$ave=$ave/$c if $c>0;
$avesqr=sqrt($avesqr/$c-$ave**2) if $c>0;
$avesqr=$avesqr/sqrt($c) if $c>0;
print sprintf("%4.3f",$ave)," +/- ",sprintf("%4.3f",$avesqr),"\n";
